# Skicka
FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive
  
RUN apt-get update \
  && apt-get install --yes --no-install-recommends \
    build-essential \
    ca-cacert \
    ca-certificates \
    git \
    golang-go \
    wget \
  && rm -rf /var/lib/apt/lists/*
  
RUN go get github.com/google/skicka && \
  go build github.com/google/skicka && \
  ln -s /root/go/bin/skicka /usr/local/bin/skicka