FROM ubuntu:18.04

RUN apt-get update \
  && apt-get install --yes --no-install-recommends \
    build-essential \
    ca-certificates \
    curl \
    git \
    libffi-dev \
    libgmp-dev \
    netbase \
    software-properties-common \
    sudo \
    wget \
    zlib1g-dev \
  && rm -rf /var/lib/apt/lists/*

ENV PATH $PATH:/root/.local/bin

RUN cd /tmp && \
  curl -sSL https://get.haskellstack.org/ | sh && \
  stack update && \
  stack setup

