# Coq
FROM ubuntu:16.04

RUN apt-get update \
  && apt-get install --yes --no-install-recommends \
    git \
    language-pack-ja \
    language-pack-ja-base \
    m4 \
    make \
    opam \
    software-properties-common \
  && rm -rf /var/lib/apt/lists/*

# Install Coq, SSReflect, and MathComp
RUN opam init --comp=4.05.0 --yes \
  && opam switch 4.05.0 \
  && eval `opam config env` \
  && opam install camlp5 \
  && opam install ocamlfind \
  && opam repo add coq-released https://coq.inria.fr/opam/released \
  && opam install coq.8.7.0 \
  && opam install coq-mathcomp-ssreflect.1.6.2 coq-mathcomp-algebra \
  && opam update \
  && opam upgrade
ENV PATH $PATH:/root/.opam/4.05.0/bin

# Install Emacs25
RUN add-apt-repository ppa:kelleyk/emacs \
  && apt-get update \
  && apt-get install --yes --no-install-recommends \
    emacs25 \
  && rm -rf /var/lib/apt/lists/*

# Install Proof General
RUN  git clone https://github.com/ProofGeneral/PG ~/.emacs.d/lisp/PG \
  && cd ~/.emacs.d/lisp/PG \
  && make \
  && echo "(load \"~/.emacs.d/lisp/PG/generic/proof-site\")" >> ~/.emacs

# Japanese
RUN locale-gen ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP.UTF-8
ENV LC_ALL ja_JP.UTF-8
