# GCC 6
FROM ubuntu:16.04

RUN apt-get update \
  && apt-get install --yes --no-install-recommends \
    build-essential \
    emacs \
    cmake \
    libboost-all-dev \
    software-properties-common

RUN add-apt-repository ppa:ubuntu-toolchain-r/test

RUN apt-get update \
  && apt-get install --yes --no-install-recommends \
    gcc-6 \
    g++-6 \
  && rm -rf /var/lib/apt/lists/*

ENV CC=/usr/bin/gcc-6
ENV CXX=/usr/bin/g++-6
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
