FROM ubuntu:18.04

RUN apt-get update && \
  apt-get install  --yes --no-install-recommends \
    build-essential \
    ca-cacert \
    ca-certificates \
    curl \
    git \
    m4 \
    unzip \
    wget && \
  rm -rf /var/lib/apt/lists/*

RUN curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh > /tmp/install.sh && \
  echo "/usr/local/bin" > /tmp/bindir && \
  sh /tmp/install.sh < /tmp/bindir && \
  rm /tmp/bindir /tmp/insatall.sh

RUN opam init --comp 4.06.0 --disable-sandboxing && \
  opam switch 4.06.0 && \
  eval `opam env`

RUN opam repository add satysfi-external https://github.com/gfngfn/satysfi-external-repo.git && \
  opam update

RUN git clone https://github.com/gfngfn/SATySFi.git && \
  cd /SATySFi && \
  opam pin add --yes satysfi . && \
  opam install --yes satysfi

ENV PATH $PATH:/root/.opam/4.06.0/bin

RUN cd /SATySFi && \
  ./download-fonts.sh && \
  ./install-libs.sh
