# LaTeX
FROM ubuntu:16.04

RUN apt-get update \
  && apt-get install --yes --no-install-recommends \
    build-essential \
    emacs \
    cmake \
    texlive-full \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
  && apt-get install --yes --no-install-recommends \
     python-dev \
     python3-dev \
     python-pip \
     python3-pip \
  && rm -rf /var/lib/apt/lists/*

RUN pip install Pygments
